server:
  port: 8080
spring:
  application:
    name: 'meudoc-api'
  data:
    mongodb:
      authentication-database: meudoc
      host: localhost
      port: 27017
      database: meudoc
      username: meudoc
      password: meudoc
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


