
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/dirceu/dev/workspaces/spring-tools/microservice-repo
